spring:
  profiles:
    active: test
calculator:
  database:
    db: u726612052_calculator
    host: 185.28.21.1
    username: u726612052_calcuser
    password: wYspih-gompyx-1tadte
    driver-class-name: com.mysql.cj.jdbc.Driver
