spring:
  profiles:
    active: dev
calculator:
  database:
    db: calculatordb
    host: 127.0.0.1
    username: calculatoruser
    password: ntdcalculator123
    driver-class-name: com.mysql.cj.jdbc.Driver
